name: Уязвимость
description: Ошибка, о которой не стоит говоорить публично
labels: [status:triage, type:bug, priority:urgent]
body:
  - type: markdown
    attributes:
      value: |
        О серьезных уязвимостях лучше не говорить открыто, так как их смогут использовать другие. В данный момент такие вещи надо сообщать лично chelog'у:
        - Discord: chelog#8888
        - VK: https://vk.com/chelog
        - Почта: chelog@octothorp.team
