blank_issues_enable: false
contact_links:
  - name: 💡 Предложение
    url: https://github.com/octothorp-team/public-dobrograd/discussions
    about: Пожелание для дальнейшего развития
  - name: 🔓 Уязвимость
    url: https://wiki.octothorp.team/ru/bug-report/confidential
    about: Ошибка, о которой не стоит говоорить публично
   
